// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		double larger = 0.0; 
		double smallerEqual = 0.0;
		for (int i = 0; i < N; i++) {
			if (Math.random() > 0.5) {
				larger++;
			} else {
				smallerEqual++;
			}
		}
		System.out.println("> 0.5:  " + (int) larger + " times");
		System.out.println("<= 0.5: " + (int) smallerEqual + " times");
		if (larger != 0 && smallerEqual != 0) {
			System.out.println("Ratio: " +  Math.min((larger / smallerEqual), (smallerEqual / larger)));
		}
	}
}
